### ISSUE TITLE
Issue: Null Values in self-hosted API Response

### ISSUE THREAD

**Issue by TanuTSure** [open-meteo/open-meteo#1210]
I have encountered an issue with my self-hosted OpenMeteo API. Some columns in the API responses contain null values. The problem started occurring on 2025-01-08 and persists to the current date.

The issue occurs consistently for queries made to the /v1/archive endpoint using the era5 historical model.

Steps to Reproduce

1. Run the following Python code to query the API:

```
import os
import sys
import openmeteo_requests
import pandas as pd
from retry_requests import retry
import requests_cache

def setup_requests_cache():
    """
    Sets up the request caching with retries for external API requests.

    Returns:
        session (requests.Session): A session object with caching and retry logic.
    """
    cache_session = requests_cache.CachedSession(".cache", expire_after=-1)
    return retry(cache_session, retries=5, backoff_factor=0.2)


session = setup_requests_cache()
openmeteo = openmeteo_requests.Client(session=session)
url = "http://localhost:80/v1/archive"
params = {
        "latitude": 16.202,
        "longitude": 103.276,
        "timezone": "Asia/Bangkok",
        "start_date": "2025-01-06",
        "end_date": "2025-01-20",
        "hourly": ["temperature_2m", "weather_code"],
        "daily": ["weather_code", "temperature_2m_max", "temperature_2m_min", "temperature_2m_mean", "apparent_temperature_max", "apparent_temperature_min", "apparent_temperature_mean", "precipitation_sum", "precipitation_hours"],
        "models": "era5"
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation {response.Elevation()} m asl")
print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

# Process daily data. The order of variables needs to be the same as requested.
daily = response.Daily()
daily_weather_code = daily.Variables(0).ValuesAsNumpy()
daily_temperature_2m_max = daily.Variables(1).ValuesAsNumpy()
daily_temperature_2m_min = daily.Variables(2).ValuesAsNumpy()
daily_temperature_2m_mean = daily.Variables(3).ValuesAsNumpy()
daily_apparent_temperature_max = daily.Variables(4).ValuesAsNumpy()
daily_apparent_temperature_min = daily.Variables(5).ValuesAsNumpy()
daily_apparent_temperature_mean = daily.Variables(6).ValuesAsNumpy()
daily_precipitation_sum = daily.Variables(7).ValuesAsNumpy()
daily_precipitation_hours = daily.Variables(8).ValuesAsNumpy()

daily_data = {"date": pd.date_range(
	start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
	end = pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = daily.Interval()),
	inclusive = "left"
)}

daily_data["weather_code"] = daily_weather_code
daily_data["temperature_2m_max"] = daily_temperature_2m_max
daily_data["temperature_2m_min"] = daily_temperature_2m_min
daily_data["temperature_2m_mean"] = daily_temperature_2m_mean
daily_data["apparent_temperature_max"] = daily_apparent_temperature_max
daily_data["apparent_temperature_min"] = daily_apparent_temperature_min
daily_data["apparent_temperature_mean"] = daily_apparent_temperature_mean
daily_data["precipitation_sum"] = daily_precipitation_sum
daily_data["precipitation_hours"] = daily_precipitation_hours

```
2.Inspect the output data or save it to a CSV file:

```
daily_dataframe = pd.DataFrame(data=daily_data)
daily_dataframe.to_csv("weather.csv", index=False, header=True)
```

3.Check the weather.csv file or printed output.

Expected Behavior

Daily data columns should contain valid values for the queried date range.

Actual Behavior

The data contains null values for all requested daily variables starting from 2025-01-08:
```
date,weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,precipitation_sum,precipitation_hours
2025-01-08 17:00:00+00:00,,,,,,,,,0.0
2025-01-09 17:00:00+00:00,,,,,,,,,0.0
2025-01-10 17:00:00+00:00,,,,,,,,,0.0
2025-01-11 17:00:00+00:00,,,,,,,,,0.0
2025-01-12 17:00:00+00:00,,,,,,,,,0.0
2025-01-13 17:00:00+00:00,,,,,,,,,0.0
2025-01-14 17:00:00+00:00,,,,,,,,,0.0
2025-01-15 17:00:00+00:00,,,,,,,,,0.0
2025-01-16 17:00:00+00:00,,,,,,,,,0.0
2025-01-17 17:00:00+00:00,,,,,,,,,0.0
2025-01-18 17:00:00+00:00,,,,,,,,,0.0
2025-01-19 17:00:00+00:00,,,,,,,,,0.0
```

.env file
```
OPEN_METEO_MODELS_HISTORICAL=copernicus_era5
OPEN_METEO_VARIABLES_HISTORICAL=boundary_layer_height,cloud_cover,cloud_cover_high,cloud_cover_low,cloud_cover_mid,dew_point_2m,direct_radiation,precipitation,pressure_msl,shortwave_radiation,snowfall_water_equivalent,soil_moisture_0_to_7cm,soil_moisture_100_to_255cm,soil_moisture_28_to_100cm,soil_moisture_7_to_28cm,soil_temperature_0_to_7cm,soil_temperature_100_to_255cm,soil_temperature_28_to_100cm,soil_temperature_7_to_28cm,static,temperature_2m,total_column_integrated_water_vapour,wind_gusts_10m,wind_u_component_100m,wind_u_component_10m,wind_v_component_100m,wind_v_component_10m
OPEN_METEO_MAX_AGE_DAYS_HISTORICAL=20
OPEN_METEO_REPEAT_INTERVAL_HISTORICAL=1440
OPEN_METEO_CONCURRENT_HISTORICAL=4
```

**Comment by patrick-zippenfenig** [comment]
Hi, can you make sure to run the latest `1.4.0` docker images?

**Comment by TanuTSure** [comment]
I am already using the latest 1.4.0 version. Below is my Docker Compose file for reference:
```
version: '3.8'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-info}

services:
  open-meteo-api:
    image: ghcr.io/open-meteo/open-meteo:1.4.0
    container_name: open-meteo-api
    ports:
      - "80:8080"
    command: serve
    volumes:
      - weather_data:/app/data
    restart: always
    env_file:
    - .env.example 
    environment:
      <<: *shared_environment
    networks:
      - openmeteo-network

  open-meteo-sync-forecast:
    image: ghcr.io/open-meteo/open-meteo:1.4.0
    container_name: open-meteo-sync-forecast
    command: sync ${OPEN_METEO_MODELS_FORECAST} ${OPEN_METEO_VARIABLES_FORECAST} --past-days ${OPEN_METEO_MAX_AGE_DAYS_FORECAST} --repeat-interval ${OPEN_METEO_REPEAT_INTERVAL_FORECAST} --concurrent ${OPEN_METEO_CONCURRENT_FORECAST}
    volumes:
      - weather_data:/app/data
    restart: always
    env_file:
    - .env.example 
    environment:
      <<: *shared_environment
      OPEN_METEO_MODELS_FORECAST: ${OPEN_METEO_MODELS_FORECAST}
      OPEN_METEO_VARIABLES_FORECAST: ${OPEN_METEO_VARIABLES_FORECAST}
      OPEN_METEO_MAX_AGE_DAYS_FORECAST: ${OPEN_METEO_MAX_AGE_DAYS_FORECAST}
      OPEN_METEO_REPEAT_INTERVAL_FORECAST: ${OPEN_METEO_REPEAT_INTERVAL_FORECAST}
      OPEN_METEO_CONCURRENT_FORECAST: ${OPEN_METEO_CONCURRENT_FORECAST}
    networks:
      - openmeteo-network

  open-meteo-sync-historical:
    image: ghcr.io/open-meteo/open-meteo:1.4.0
    container_name: open-meteo-sync-historical
    command: sync ${OPEN_METEO_MODELS_HISTORICAL} ${OPEN_METEO_VARIABLES_HISTORICAL} --past-days ${OPEN_METEO_MAX_AGE_DAYS_HISTORICAL} --repeat-interval ${OPEN_METEO_REPEAT_INTERVAL_HISTORICAL} --concurrent ${OPEN_METEO_CONCURRENT_HISTORICAL}
    volumes:
      - weather_data:/app/data
    restart: always
    env_file:
    - .env.example 
    environment:
      <<: *shared_environment
      OPEN_METEO_MODELS_HISTORICAL: ${OPEN_METEO_MODELS_HISTORICAL}
      OPEN_METEO_VARIABLES_HISTORICAL: ${OPEN_METEO_VARIABLES_HISTORICAL}
      OPEN_METEO_MAX_AGE_DAYS_HISTORICAL: ${OPEN_METEO_MAX_AGE_DAYS_HISTORICAL}
      OPEN_METEO_REPEAT_INTERVAL_HISTORICAL: ${OPEN_METEO_REPEAT_INTERVAL_HISTORICAL}
      OPEN_METEO_CONCURRENT_HISTORICAL: ${OPEN_METEO_CONCURRENT_HISTORICAL}
    networks:
      - openmeteo-network

```
