### ISSUE TITLE
docker container just exits

### ISSUE THREAD

**Issue by hemna** [open-meteo/open-meteo#406]
I am trying to follow the instructions here:
https://github.com/open-meteo/open-meteo/blob/main/docs/getting-started.md

And I have also created my own docker-compose.yml file to start the API container.  

The container simply exits with code 0.

My docker-compose.yml

```
version: "3.3"

services:
  open-meteo:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo
    volumes:
        - ./data:/app/data
    ports:
      - 8888:8080
    restart: unless-stopped
```

```
└─> docker compose up
[+] Running 1/1
 ✔ Container open-meteo  Recreated                                                                                                       0.1s
Attaching to open-meteo
open-meteo exited with code 0
```

Trying to run directly, it also simply exits.

```
╭─waboring in dl360-2 in ~/docker/open-meteo ❯
└─> docker run --rm -v ${PWD}/data:/app/data -p 8888:8080 ghcr.io/open-meteo/open-meteo
╭─waboring in dl360-2 in ~/docker/open-meteo ❯
```
